# Site settings
baseurl = "liyong.github.io"
languageCode = "en-us"
title = "Hugo Identity Theme"
theme = "hugo-identity-theme"
themesDir = "../"

# Disable unnecessary kinds
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-XXXXX-Y"

[params]

  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  favicon_ico = "favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  #Additional options to supplement icons served
  #favicon_png = "favicon.png"
  #favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"
  
  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  #custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = " Yong Li"
    school = "University of Maryland, College Park"
    # Avatars can be written to images/avatars/
    avatar = "pic.jpeg"
    position = "CS and ECON"
    livesIn = "SWE Intern @ [NASA GODDARD](https://www.nasa.gov/goddard)"
    #scope = [
    #    "Software Engineering Intern for [NASA GODDARD](https://www.nasa.gov/goddard)",
    #    "Maintainer for [awesome-project](#)",
    #    "Open Source [community management](#)"
    #  ]
    # biography = """?????"""

  # Contact form settings

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "liyong2123@gmail.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://example.com/mailout/"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting us."
    error = "Message could not be send. Please contact us at "

    # Google invisible captcha
    #[params.contact.captcha]
    #  sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others
  [[params.social2]]
    title = "Music"
    icon = "fa-music"
  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin"
    link = "https://www.linkedin.com/in/yong-li-0301/"
    target = "_blank"
  [[params.social]]
    title = "Resume"
    icon = "fa-file-text-o"
    link = "assets/Yong Li.pdf"
    target = "_blank"
    
  [[params.social]]
    title = "Github"
    icon = "fa-github"
    link = "https://github.com/liyong2123"
    target = "_blank"




 

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="
